name: Build
'on':
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build-and-test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Linting
        run: bun run lint
      - name: Run build job
        run: |
          cd apps/extension
          bun run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ai-prompt-snippets
          path: apps/extension/dist

  playwright:
    name: Playwright Tests
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: ai-prompt-snippets
      - name: Install dependencies
        run: bun install
      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps
      - name: Run Playwright tests
        run: bun run e2e:headless