name: Build and Test
'on':
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build-and-test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Linting
        run: bun run lint
      - name: Run build job
        run: |
          cd apps/extension
          bun run build
      - name: Upload Artifact
        if: matrix.job == 'build' && success()
        uses: actions/upload-artifact@v3
        with:
          name: ai-prompt-snippets
          path: apps/extension/dist

  playwright:
    name: Playwright Tests
    runs-on: ubuntu-latest
    needs: build-and-test
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-jammy
    steps:
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: ai-prompt-snippets
      - name: Run your tests
        run: ls -al
