name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-test:
    name: Build And Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job: [build, lint]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Linting
        if: matrix.job == 'lint'
        run: bun run lint

      - name: Build extension
        if: matrix.job == 'build'
        run: cd apps/plugin && bun run build && ls -al

