name: e2e
'on':
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
jobs:
  playwright:
    name: Playwright Tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-jammy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: "build.yml"
      - name: Run your tests
        run: ls -al
