name: Test
'on':
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
jobs:
  playwright:
    name: Playwright Tests
    runs-on: ubuntu-latest
    needs: build-and-test
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-jammy
    steps:
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
      - name: Run your tests
        run: ls -al
